// src/components/home/Experience.jsx
import React from 'react';
import experienceData from '../../data/experience.json';

const Experience = () => {
  return (
    <div className="container mx-auto">
      <h2 className="text-3xl font-bold text-center mb-10">Experience</h2>
      <div className="grid mx-8 md:grid-cols-2 gap-8">
        {experienceData.map((experience, index) => (
          <div
            key={index}
            className="flex flex-col md:flex-row items-center mb-8 bg-white shadow-md rounded-lg overflow-hidden hover:shadow-lg hover:transform hover:scale-105 transition duration-300"
          >
            <img src={experience.image} alt={experience.position} className="w-1/4 object-cover" />
            <div className="flex-1 mx-4">
              <p className="font-bold">
                {experience.position} - {""}
                <a
                  href={experience.link}
                  className="text-blue-500 hover:text-blue-600"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {experience.company}
                </a>
              </p>
              <p className="text-lg">{experience.year}</p>
              <ul className="list-disc list-inside">
                {experience.description.map((desc, descIndex) => (
                  <li key={descIndex}>{desc}</li>
                ))}
              </ul>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Experience;

// src/routes/experience.svelte
<!-- ExperienceSection.svelte -->
<script>
  // Define experience data (replace this with your actual experience data)
  const experienceData = [
    {
      year: "2018 - Present",
      position: "Software Engineer",
      description: [
        "Developed and maintained web applications using React.js and Node.js.",
        "Collaborated with cross-functional teams to deliver high-quality software products.",
        "Implemented responsive UI designs to improve user experience."
      ],
      socialMediaLinks: [
        { icon: "fab fa-twitter", url: "/" },
        { icon: "fab fa-linkedin", url: "/" },
        { icon: "fab fa-github", url: "/" }
      ]
    },
    {
      year: "2016 - 2018",
      position: "Frontend Developer",
      description: [
        "Designed and developed user interfaces for mobile and web applications.",
        "Worked closely with UX designers to ensure intuitive user interaction.",
        "Optimized website performance and accessibility."
      ],
      socialMediaLinks: [
        { icon: "fab fa-twitter", url: "/" },
        { icon: "fab fa-linkedin", url: "/" },
        { icon: "fab fa-github", url: "/" }
      ]
    },
    {
      year: "2014 - 2016",
      position: "Software Developer",
      description: [
        "Developed software solutions for clients in various industries.",
        "Collaborated with project managers to deliver projects on time and within budget.",
        "Provided technical support and training to end users."
      ],
      socialMediaLinks: [
        { icon: "fab fa-twitter", url: "/" },
        { icon: "fab fa-linkedin", url: "/" },
        { icon: "fab fa-github", url: "/" }
      ]
    }
  ];
</script>

<div class="container mx-auto py-8">
  <h2 class="text-3xl font-bold mb-4 text-center">Experience</h2>
  
  {#each experienceData as experience}
    <div class="mx-12 px-4 flex items-center mb-8 bg-white shadow-md rounded-lg overflow-hidden hover:shadow-lg hover:transform hover:scale-105 transition duration-300">
      <div class="flex-1 mr-4">
        <p class="font-bold">{experience.year}</p>
        <p class="text-lg">{experience.position}</p>
        <ul class="list-disc list-inside">
          {#each experience.description as desc}
            <li>{desc}</li>
          {/each}
        </ul>
      </div>
      <div class="w-32 h-32 flex items-center justify-center bg-white shadow-md rounded-lg mr-4">
        <!-- Replace the placeholder image URL with your actual company logo -->
        <img src="avatar.png" alt="Company Logo" class="w-full h-full object-contain">
      </div>
      <div class="flex">
        {#each experience.socialMediaLinks as link}
          <a href={link.url} class="text-blue-500 hover:text-blue-600 mx-2"><i class={link.icon}></i></a>
        {/each}
      </div>
    </div>
    <hr class="my-8">
  {/each}
</div>

<style>
  /* Add any additional styles here */
</style>
